# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cfctl < Formula
  desc "Command-line interface for SpaceONE"
  homepage "https://github.com/cloudforet-io/cfctl"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/cloudforet-io/cfctl/releases/download/v1.0.0/cfctl_Darwin_x86_64.tar.gz"
      sha256 "7f2bb2f6d23f24c3321ad683d06586d496d321e1bc34ea4bbe3bf7d5caf7abe2"

      def install
        bin.install "cfctl"
      end
    end
    on_arm do
      url "https://github.com/cloudforet-io/cfctl/releases/download/v1.0.0/cfctl_Darwin_arm64.tar.gz"
      sha256 "aa91724cb252ef9d5de329e5fff3587546e7b8d05e5a18a7eae08d64ef85cbc6"

      def install
        bin.install "cfctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudforet-io/cfctl/releases/download/v1.0.0/cfctl_Linux_x86_64.tar.gz"
        sha256 "ed6f6f1521b0f50b5195210ef8badc30a4fecdc392955a8369bd457c9a99e3f1"

        def install
          bin.install "cfctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudforet-io/cfctl/releases/download/v1.0.0/cfctl_Linux_arm64.tar.gz"
        sha256 "8a68123a99e7a894c7fa27dfb2c937a7befc48d3deb4ad6cbb0ee25ffd9e0c8f"

        def install
          bin.install "cfctl"
        end
      end
    end
  end

  test do
    system "#{bin}/cfctl version"
  end
end
