# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cfctl < Formula
  desc "Command-line interface for SpaceONE"
  homepage "https://github.com/cloudforet-io/cfctl"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/cloudforet-io/cfctl/releases/download/v1.0.0/cfctl_Darwin_x86_64.tar.gz"
      sha256 "96bf082210ade3bce5c4af366af30fb448c67e137db8f12b2c8c587b599f6045"

      def install
        bin.install "cfctl"
      end
    end
    on_arm do
      url "https://github.com/cloudforet-io/cfctl/releases/download/v1.0.0/cfctl_Darwin_arm64.tar.gz"
      sha256 "c1cccb612c8dd3072639f94fef44e84966ebecc15e8a5963c73ed4643b539787"

      def install
        bin.install "cfctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudforet-io/cfctl/releases/download/v1.0.0/cfctl_Linux_x86_64.tar.gz"
        sha256 "32e5d06cb3ecc73ee89644703b8082ac53bd31f2987abb29c970bf23e31472db"

        def install
          bin.install "cfctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudforet-io/cfctl/releases/download/v1.0.0/cfctl_Linux_arm64.tar.gz"
        sha256 "b31f87855d3e268ca8f47bf1a652c6af292e16f67b8b692de41dada90ee4686a"

        def install
          bin.install "cfctl"
        end
      end
    end
  end

  test do
    system "#{bin}/cfctl version"
  end
end
