# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cfctl < Formula
  desc "Command-line interface for SpaceONE"
  homepage "https://github.com/cloudforet-io/cfctl"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/cloudforet-io/cfctl/releases/download/v1.0.0/cfctl_Darwin_x86_64.tar.gz"
      sha256 "731e12c86c90703b787872904eed54e12926d60c1ab14237b3f495c76564b724"

      def install
        bin.install "cfctl"
      end
    end
    on_arm do
      url "https://github.com/cloudforet-io/cfctl/releases/download/v1.0.0/cfctl_Darwin_arm64.tar.gz"
      sha256 "436b3616e461c71cd2b1bceae3f8caf7828ae2b03ae8ebe0fcdba4346f4a1dba"

      def install
        bin.install "cfctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudforet-io/cfctl/releases/download/v1.0.0/cfctl_Linux_x86_64.tar.gz"
        sha256 "989a8517d23331a0fe804aa88f260e9b2fa7a6cedffe062ef4ff37792775d84e"

        def install
          bin.install "cfctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudforet-io/cfctl/releases/download/v1.0.0/cfctl_Linux_arm64.tar.gz"
        sha256 "41683ea95f02662d1b97a974faad8d2e81e9ecc06f4ef420f9175123b03b2b08"

        def install
          bin.install "cfctl"
        end
      end
    end
  end

  test do
    system "#{bin}/cfctl version"
  end
end
