# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cfctl < Formula
  desc "Command-line interface for SpaceONE"
  homepage "https://github.com/cloudforet-io/cfctl"
  version "1.0.15"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/cloudforet-io/cfctl/releases/download/v1.0.15/cfctl_Darwin_x86_64.tar.gz"
      sha256 "fb2203f29d35e328c1ef5b84e3d2a4f8731c2ee813f76705669609b418cfae43"

      def install
        bin.install "cfctl"
      end
    end
    on_arm do
      url "https://github.com/cloudforet-io/cfctl/releases/download/v1.0.15/cfctl_Darwin_arm64.tar.gz"
      sha256 "1ecfed5477f14cdf75d6ffc139126793a529395d2542fe857e2d90dc1ab06071"

      def install
        bin.install "cfctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudforet-io/cfctl/releases/download/v1.0.15/cfctl_Linux_x86_64.tar.gz"
        sha256 "d53333834b70ee464bfba7cfd5b3b52bd65955fb092ff2d94db2de1ece1b7b1a"

        def install
          bin.install "cfctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudforet-io/cfctl/releases/download/v1.0.15/cfctl_Linux_arm64.tar.gz"
        sha256 "7e54546ce775340afcf0843f54eed3858c55ba84db6fad69472ddb70d7ea824b"

        def install
          bin.install "cfctl"
        end
      end
    end
  end

  test do
    system "#{bin}/cfctl version"
  end
end
