# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cfctl < Formula
  desc "Command-line interface for SpaceONE"
  homepage "https://github.com/cloudforet-io/cfctl"
  version "1.0.2"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/cloudforet-io/cfctl/releases/download/v1.0.2/cfctl_Darwin_x86_64.tar.gz"
      sha256 "2928f0b3397ec1961da05595eafc0ae5bb46c5c9f9ce80910ee39bd21b3a82cf"

      def install
        bin.install "cfctl"
      end
    end
    on_arm do
      url "https://github.com/cloudforet-io/cfctl/releases/download/v1.0.2/cfctl_Darwin_arm64.tar.gz"
      sha256 "eca659eb374046f18ea94d36ece22b010c5ed1ed3d89842593cd9e55048e5fcf"

      def install
        bin.install "cfctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudforet-io/cfctl/releases/download/v1.0.2/cfctl_Linux_x86_64.tar.gz"
        sha256 "87e90c632940d0e2cea2d477975ff87dbc6cbfa4a5dbe5adfa15a771c71ff55b"

        def install
          bin.install "cfctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudforet-io/cfctl/releases/download/v1.0.2/cfctl_Linux_arm64.tar.gz"
        sha256 "afd76765d5b1cabcd1d8f167b1e7a40d243297b3ab5e5b33116eef9c3df0eba2"

        def install
          bin.install "cfctl"
        end
      end
    end
  end

  test do
    system "#{bin}/cfctl version"
  end
end
